# Generated by Django 4.2.11 on 2026-04-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surprisebag',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bag_images/'),
        ),
    ]
