# Generated by Django 4.2.11 on 2026-04-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_contact_email_store_owner_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
