# Generated by Django 4.2.11 on 2026-05-04 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_alter_store_category_alter_store_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='area',
            field=models.CharField(choices=[('johar_town', 'Johar Town'), ('wafaqi_colony', 'Wafaqi Colony'), ('muslim_town', 'Muslim Town'), ('gulberg', 'Gulberg'), ('model_town', 'Model Town'), ('garden_town', 'Garden Town'), ('faisal_town', 'Faisal Town'), ('township', 'Township'), ('iqbal_town', 'Iqbal Town'), ('other', 'Other')], default='johar_town', max_length=100),
        ),
    ]
